# Generated by Django 5.0.1 on 2024-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unmid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
