# Generated by Django 5.0.1 on 2024-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Staff', 'Staff'), ('Student', 'Student'), ('Supervisor', 'Supervisor')], default='Student', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='unmid',
            field=models.IntegerField(default=1),
        ),
    ]
