# Generated by Django 5.0.1 on 2024-01-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_access_employee_phonenumber_employee_unmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Administrator', 'Administrator'), ('Staff', 'Staff'), ('Student', 'Student'), ('Supervisor', 'Supervisor')], max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='No Last Name', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'access': 'Administrator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisees', to='employee.employee'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='access',
        ),
        migrations.AddField(
            model_name='employee',
            name='access',
            field=models.ManyToManyField(blank=True, to='employee.access'),
        ),
    ]
