# Generated by Django 5.0.1 on 2024-01-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_access_rename_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
