# Generated by Django 5.0.1 on 2024-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_available',
            field=models.IntegerField(choices=[(1, 'Available'), (0, 'Unavailable')], default=1),
        ),
    ]
