# Generated by Django 5.0.1 on 2024-01-08 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_shift_is_available'),
        ('employee', '0002_employee_access_employee_phonenumber_employee_unmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='pod',
            name='building',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='day',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_available',
        ),
        migrations.AddField(
            model_name='pod',
            name='full_location_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='pod',
            name='location_name',
            field=models.CharField(default='NULL', max_length=32),
        ),
        migrations.AddField(
            model_name='pod',
            name='room_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shift',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_shifts', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_repeats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_slots',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='active',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1),
        ),
        migrations.AlterField(
            model_name='pod',
            name='building_info',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='common.terms'),
        ),
    ]
